// <auto-generated />
using System;
using BookingApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingApi.Domain.Entities.ActivityEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Messages")
                        .HasColumnType("integer");

                    b.Property<int>("Reactions")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueGroups")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityEvents");

                    b.HasData(
                        new
                        {
                            EventId = "E-1",
                            Date = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Messages = 13,
                            Reactions = 7,
                            UniqueGroups = 1,
                            UserId = "U1"
                        },
                        new
                        {
                            EventId = "E-2",
                            Date = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Messages = 33,
                            Reactions = 5,
                            UniqueGroups = 3,
                            UserId = "U1"
                        },
                        new
                        {
                            EventId = "E-3",
                            Date = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Messages = 12,
                            Reactions = 23,
                            UniqueGroups = 3,
                            UserId = "U1"
                        },
                        new
                        {
                            EventId = "E-4",
                            Date = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Messages = 27,
                            Reactions = 25,
                            UniqueGroups = 1,
                            UserId = "U1"
                        },
                        new
                        {
                            EventId = "E-5",
                            Date = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Messages = 19,
                            Reactions = 8,
                            UniqueGroups = 1,
                            UserId = "U1"
                        },
                        new
                        {
                            EventId = "E-6",
                            Date = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Messages = 25,
                            Reactions = 19,
                            UniqueGroups = 1,
                            UserId = "U1"
                        },
                        new
                        {
                            EventId = "E-7",
                            Date = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Messages = 420,
                            Reactions = 21,
                            UniqueGroups = 3,
                            UserId = "U1"
                        });
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.Badge", b =>
                {
                    b.Property<string>("BadgeId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("BadgeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("BadgeId");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            BadgeId = "B1",
                            BadgeName = "🥉 Bronz Sosyal",
                            Condition = "total_points >= 200",
                            Level = 1
                        },
                        new
                        {
                            BadgeId = "B2",
                            BadgeName = "🥈 Gümüş Sosyal",
                            Condition = "total_points >= 600",
                            Level = 2
                        },
                        new
                        {
                            BadgeId = "B3",
                            BadgeName = "🥇 Altın Sosyal",
                            Condition = "total_points >= 1000",
                            Level = 3
                        });
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.BadgeAward", b =>
                {
                    b.Property<string>("AwardId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BadgeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("AwardId");

                    b.HasIndex("BadgeId");

                    b.HasIndex("UserId");

                    b.ToTable("BadgeAwards");

                    b.HasData(
                        new
                        {
                            AwardId = "BA-1",
                            BadgeId = "B1",
                            UserId = "U1"
                        },
                        new
                        {
                            AwardId = "BA-2",
                            BadgeId = "B1",
                            UserId = "U2"
                        },
                        new
                        {
                            AwardId = "BA-3",
                            BadgeId = "B1",
                            UserId = "U3"
                        },
                        new
                        {
                            AwardId = "BA-4",
                            BadgeId = "B1",
                            UserId = "U4"
                        });
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.Challenge", b =>
                {
                    b.Property<string>("ChallengeId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ChallengeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("integer");

                    b.HasKey("ChallengeId");

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            ChallengeId = "C-01",
                            ChallengeName = "Günlük Mesajcı",
                            Condition = "messages_today >= 20",
                            IsActive = true,
                            Priority = 4,
                            RewardPoints = 50
                        },
                        new
                        {
                            ChallengeId = "C-02",
                            ChallengeName = "Etkileşim Ustası",
                            Condition = "reactions_today >= 15",
                            IsActive = true,
                            Priority = 3,
                            RewardPoints = 80
                        },
                        new
                        {
                            ChallengeId = "C-03",
                            ChallengeName = "Grup Lideri",
                            Condition = "unique_groups_today >= 3",
                            IsActive = true,
                            Priority = 2,
                            RewardPoints = 120
                        },
                        new
                        {
                            ChallengeId = "C-04",
                            ChallengeName = "Haftalık Aktif",
                            Condition = "messages_7d >= 150",
                            IsActive = true,
                            Priority = 1,
                            RewardPoints = 200
                        });
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.ChallengeAward", b =>
                {
                    b.Property<string>("AwardId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("AsOfDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChallengeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("AwardId");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId");

                    b.ToTable("ChallengeAwards");
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.Group", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = "G1",
                            GroupName = "Tech Sohbet"
                        },
                        new
                        {
                            GroupId = "G2",
                            GroupName = "Futbol Muhabbet"
                        },
                        new
                        {
                            GroupId = "G3",
                            GroupName = "Oyun Ekibi"
                        });
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.PointsLedger", b =>
                {
                    b.Property<string>("LedgerId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("PointsDelta")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("LedgerId");

                    b.HasIndex("UserId");

                    b.ToTable("PointsLedgers");

                    b.HasData(
                        new
                        {
                            LedgerId = "L-200",
                            PointsDelta = 200,
                            Source = "CHALLENGE",
                            SourceRef = "A-100",
                            UserId = "U1"
                        },
                        new
                        {
                            LedgerId = "L-201",
                            PointsDelta = 200,
                            Source = "CHALLENGE",
                            SourceRef = "A-101",
                            UserId = "U2"
                        },
                        new
                        {
                            LedgerId = "L-202",
                            PointsDelta = 200,
                            Source = "CHALLENGE",
                            SourceRef = "A-102",
                            UserId = "U3"
                        },
                        new
                        {
                            LedgerId = "L-203",
                            PointsDelta = 200,
                            Source = "CHALLENGE",
                            SourceRef = "A-103",
                            UserId = "U4"
                        },
                        new
                        {
                            LedgerId = "L-204",
                            PointsDelta = 50,
                            Source = "CHALLENGE",
                            SourceRef = "A-104",
                            UserId = "U5"
                        });
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "U1",
                            City = "Istanbul",
                            Name = "Ayşe"
                        },
                        new
                        {
                            UserId = "U2",
                            City = "Ankara",
                            Name = "Ali"
                        },
                        new
                        {
                            UserId = "U3",
                            City = "Izmir",
                            Name = "Deniz"
                        },
                        new
                        {
                            UserId = "U4",
                            City = "Bursa",
                            Name = "Mert"
                        },
                        new
                        {
                            UserId = "U5",
                            City = "Antalya",
                            Name = "Ece"
                        });
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.UserState", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("AsOfDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Messages7d")
                        .HasColumnType("integer");

                    b.Property<int>("MessagesToday")
                        .HasColumnType("integer");

                    b.Property<int>("Reactions7d")
                        .HasColumnType("integer");

                    b.Property<int>("ReactionsToday")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueGroupsToday")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "AsOfDate");

                    b.ToTable("UserStates");

                    b.HasData(
                        new
                        {
                            UserId = "U1",
                            AsOfDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Messages7d = 169,
                            MessagesToday = 420,
                            Reactions7d = 108,
                            ReactionsToday = 21,
                            UniqueGroupsToday = 3
                        },
                        new
                        {
                            UserId = "U2",
                            AsOfDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Messages7d = 150,
                            MessagesToday = 26,
                            Reactions7d = 109,
                            ReactionsToday = 8,
                            UniqueGroupsToday = 1
                        },
                        new
                        {
                            UserId = "U3",
                            AsOfDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Messages7d = 185,
                            MessagesToday = 23,
                            Reactions7d = 88,
                            ReactionsToday = 16,
                            UniqueGroupsToday = 2
                        },
                        new
                        {
                            UserId = "U4",
                            AsOfDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Messages7d = 218,
                            MessagesToday = 38,
                            Reactions7d = 129,
                            ReactionsToday = 13,
                            UniqueGroupsToday = 1
                        },
                        new
                        {
                            UserId = "U5",
                            AsOfDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Messages7d = 104,
                            MessagesToday = 29,
                            Reactions7d = 70,
                            ReactionsToday = 11,
                            UniqueGroupsToday = 1
                        });
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.ActivityEvent", b =>
                {
                    b.HasOne("BookingApi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.BadgeAward", b =>
                {
                    b.HasOne("BookingApi.Domain.Entities.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingApi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.ChallengeAward", b =>
                {
                    b.HasOne("BookingApi.Domain.Entities.Challenge", "Challenge")
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookingApi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.Notification", b =>
                {
                    b.HasOne("BookingApi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.PointsLedger", b =>
                {
                    b.HasOne("BookingApi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingApi.Domain.Entities.UserState", b =>
                {
                    b.HasOne("BookingApi.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
